database:
  host: localhost
  port: 5432
  name: crypto_tracker
  user: postgres
  password: password
  ssl_mode: disable

api:
  port: 8080
  host: 0.0.0.0

worker:
  interval: 60
  coingecko_api_url: https://api.coingecko.com/api/v3

logging:
  level: info
  format: json 